### ISSUE TITLE
Ability to query project-level credentials

### ISSUE THREAD

**Issue by virasana** [tkrzeminski/jenkins-groovy-scripts#2]
Hi There, can you please give direction as to how to query project-level credentials?  The show-all-credentials script lists only those in the system global space.

More specifically, our credentials are stored in a Folder, which uses the Folder Credentials Provider.  Do you have any support for the Folder Credentials Provider?

Many Thanks!

**Comment by tkrzeminski** [comment]
Hello @virasana , I haven't used this functionality. I suggest you play with the scripts yourself

**Comment by tkrzeminski** [comment]
Hi @virasana, we have good news because @microscotch took care of your proposal and made everything work.
 
https://github.com/tkrzeminski/jenkins-groovy-scripts/pull/9

**Comment by tkrzeminski** [comment]
Done
